### ISSUE TITLE
Map doesn't load

### ISSUE THREAD

**Issue by kPanesar** [kPanesar/lcar-bot#14]
The map fails to load on my computer. Might have something to do with the way the path to the html file is generated.

**Comment by kPanesar** [comment]
The `app_root_dir_` variable is wrong. It outputs `/home/karanvir` instead of `/home/karanvir/Documents/lcar-bot`

**Comment by mtbrobotanist** [comment]
How do you launch the program?

**Comment by kPanesar** [comment]
@mtbrobotanist I just run rqt in the terminal and start the LCAR plugin from there.

**Comment by mtbrobotanist** [comment]
Fixed it. Pull from ui and try.

**Comment by kPanesar** [comment]
I'll try it in the morning.

**Comment by kPanesar** [comment]
The latest commit fixed the issue.
